# Generated by Django 6.0.4 on 2026-04-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("sell", "Sell"), ("buy", "Buy")], max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("hindi", models.CharField(max_length=100)),
                ("variety", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=50)),
                ("price_per_kg", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("seller", models.CharField(max_length=100)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
