# Generated by Django 6.0.2 on 2026-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_listingreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
