# Generated by Django 6.0.2 on 2026-04-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
