# Generated by Django 6.0.2 on 2026-04-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_userprofile_kyc_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
    ]
